server:
  restart: always
  image: nginx
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
    - ./app/static:/app/static
  links:
    - web:web
  ports:
    - "80:80"

web:
  restart: always
  build: ./app
  working_dir: /app
  volumes:
    - ./app:/app
  expose:
    - "8000"
  command: gunicorn app:app -b :8000 --name app --log-level=debug --log-file=-
